/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  PointTracker as PointTracker
} from './components/character-sheet/point-tracker/point-tracker';

declare global {
  interface HTMLPointTrackerElement extends PointTracker, HTMLElement {
  }
  var HTMLPointTrackerElement: {
    prototype: HTMLPointTrackerElement;
    new (): HTMLPointTrackerElement;
  };
  interface HTMLElementTagNameMap {
    "point-tracker": HTMLPointTrackerElement;
  }
  interface ElementTagNameMap {
    "point-tracker": HTMLPointTrackerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "point-tracker": JSXElements.PointTrackerAttributes;
    }
  }
  namespace JSXElements {
    export interface PointTrackerAttributes extends HTMLAttributes {
      maximum?: number;
      minimum?: number;
      title?: string;
    }
  }
}


import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
    }
  }
}

