/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  EquipmentGeneric as RpgEquipmentGeneric
} from './components/character-sheet/equipment/generic/equipment-generic';

declare global {
  interface HTMLRpgEquipmentGenericElement extends RpgEquipmentGeneric, HTMLElement {
  }
  var HTMLRpgEquipmentGenericElement: {
    prototype: HTMLRpgEquipmentGenericElement;
    new (): HTMLRpgEquipmentGenericElement;
  };
  interface HTMLElementTagNameMap {
    "rpg-equipment-generic": HTMLRpgEquipmentGenericElement;
  }
  interface ElementTagNameMap {
    "rpg-equipment-generic": HTMLRpgEquipmentGenericElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "rpg-equipment-generic": JSXElements.RpgEquipmentGenericAttributes;
    }
  }
  namespace JSXElements {
    export interface RpgEquipmentGenericAttributes extends HTMLAttributes {
      name?: string;
      size?: string;
      startingCount?: number;
      weight?: number;
    }
  }
}

